name: Flujo de trabajo básico

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Mostrar mensaje
      run: echo "¡Hola desde GitHub Actions!"
